fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"

# profile module layout, default include ntp module
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
    datacat: "https://github.com/richardc/puppet-datacat.git"
    zypprepo: "https://github.com/voxpupuli/puppet-zypprepo.git"
    elasticsearch: "https://github.com/elastic/puppet-elasticsearch.git"
    yum: "https://github.com/CERIT-SC/puppet-yum.git"
    kibana: "https://github.com/elastic/puppet-kibana.git"
    logstash: "https://github.com/elastic/puppet-logstash.git"    

  symlinks:
    profile_elasticsearch: "#{source_dir}"
